export const mockMedicalRecords = [
  {
    id: "mr1",
    patientId: "1",
    patientName: "Sarah Johnson",
    recordType: "consultation" as const,
    date: "2024-10-20",
    doctorId: "doc1",
    doctorName: "Dr. John Smith",
    diagnosis: "Hypertension Stage 1",
    symptoms: ["Headache", "Dizziness", "Fatigue"],
    treatment: "Lifestyle modifications, ACE inhibitor prescribed",
    prescriptions: [
      {
        id: "rx1",
        medication: "Lisinopril",
        dosage: "10mg",
        frequency: "Once daily",
        duration: "30 days",
        instructions: "Take with food",
      },
    ],
    vitals: {
      bloodPressure: "145/92",
      heartRate: 78,
      temperature: 98.6,
      weight: 165,
      height: "5'6\"",
    },
    notes:
      "Patient reports stress at work. Recommended stress management techniques.",
    followUpDate: "2024-11-20",
    status: "active" as const,
  },
  {
    id: "mr2",
    patientId: "2",
    patientName: "Michael Brown",
    recordType: "lab-result" as const,
    date: "2024-10-18",
    doctorId: "doc2",
    doctorName: "Dr. Emily Wilson",
    diagnosis: "Diabetes Type 2 - Well Controlled",
    labResults: [
      {
        test: "HbA1c",
        result: "6.8%",
        normalRange: "<7.0%",
        status: "normal",
      },
      {
        test: "Fasting Glucose",
        result: "125 mg/dL",
        normalRange: "70-100 mg/dL",
        status: "elevated",
      },
      {
        test: "Cholesterol Total",
        result: "180 mg/dL",
        normalRange: "<200 mg/dL",
        status: "normal",
      },
    ],
    treatment: "Continue current medication regimen",
    notes: "Good glucose control. Continue monitoring.",
    followUpDate: "2024-01-18",
    status: "active" as const,
  },
  {
    id: "mr3",
    patientId: "3",
    patientName: "Emma Davis",
    recordType: "emergency" as const,
    date: "2024-10-15",
    doctorId: "doc3",
    doctorName: "Dr. Michael Johnson",
    diagnosis: "Acute Asthma Exacerbation",
    symptoms: ["Shortness of breath", "Wheezing", "Chest tightness"],
    treatment: "Nebulizer treatment, corticosteroids",
    prescriptions: [
      {
        id: "rx2",
        medication: "Albuterol Inhaler",
        dosage: "90mcg",
        frequency: "2 puffs every 4-6 hours as needed",
        duration: "30 days",
        instructions: "Shake well before use",
      },
      {
        id: "rx3",
        medication: "Prednisone",
        dosage: "20mg",
        frequency: "Once daily",
        duration: "5 days",
        instructions: "Take with food",
      },
    ],
    vitals: {
      bloodPressure: "130/85",
      heartRate: 95,
      temperature: 99.1,
      oxygenSaturation: "94%",
      respiratoryRate: 24,
    },
    notes: "Patient responded well to treatment. Discharged with action plan.",
    followUpDate: "2024-10-22",
    status: "resolved" as const,
  },
];

export const mockLabTests = [
  {
    id: "lab1",
    patientId: "1",
    patientName: "Sarah Johnson",
    testType: "Complete Blood Count",
    orderedBy: "Dr. John Smith",
    orderedDate: "2024-10-22",
    status: "pending" as const,
    priority: "routine" as const,
    instructions: "Fasting not required",
  },
  {
    id: "lab2",
    patientId: "2",
    patientName: "Michael Brown",
    testType: "Lipid Panel",
    orderedBy: "Dr. Emily Wilson",
    orderedDate: "2024-10-20",
    completedDate: "2024-10-21",
    status: "completed" as const,
    priority: "routine" as const,
    results: [
      {
        parameter: "Total Cholesterol",
        value: "180",
        unit: "mg/dL",
        range: "<200",
      },
      { parameter: "HDL", value: "45", unit: "mg/dL", range: ">40" },
      { parameter: "LDL", value: "110", unit: "mg/dL", range: "<100" },
      {
        parameter: "Triglycerides",
        value: "125",
        unit: "mg/dL",
        range: "<150",
      },
    ],
    instructions: "12-hour fasting required",
  },
  {
    id: "lab3",
    patientId: "4",
    patientName: "James Wilson",
    testType: "Cardiac Enzymes",
    orderedBy: "Dr. Michael Johnson",
    orderedDate: "2024-10-19",
    status: "urgent" as const,
    priority: "stat" as const,
    instructions: "STAT - Chest pain evaluation",
  },
];

export const mockPrescriptions = [
  {
    id: "rx1",
    patientId: "1",
    patientName: "Sarah Johnson",
    medication: "Lisinopril",
    dosage: "10mg",
    frequency: "Once daily",
    quantity: 30,
    refills: 2,
    prescribedBy: "Dr. John Smith",
    prescribedDate: "2024-10-20",
    pharmacy: "City Pharmacy",
    status: "active" as const,
    instructions: "Take with food, monitor blood pressure",
  },
  {
    id: "rx2",
    patientId: "3",
    patientName: "Emma Davis",
    medication: "Albuterol Inhaler",
    dosage: "90mcg",
    frequency: "2 puffs as needed",
    quantity: 1,
    refills: 3,
    prescribedBy: "Dr. Michael Johnson",
    prescribedDate: "2024-10-15",
    pharmacy: "Downtown Pharmacy",
    status: "active" as const,
    instructions: "Use for shortness of breath, shake before use",
  },
  {
    id: "rx3",
    patientId: "2",
    patientName: "Michael Brown",
    medication: "Metformin",
    dosage: "500mg",
    frequency: "Twice daily",
    quantity: 60,
    refills: 5,
    prescribedBy: "Dr. Emily Wilson",
    prescribedDate: "2024-09-15",
    pharmacy: "Health Plus Pharmacy",
    status: "active" as const,
    instructions: "Take with meals to reduce stomach upset",
  },
];
