export const mockAppointments = [
  {
    id: "1",
    patient: "Sarah Johnson",
    doctor: "Dr. Smith",
    date: "2024-10-25",
    time: "09:00 AM",
    type: "consultation" as const,
    status: "confirmed" as const,
    price: 150,
    notes: "Regular checkup",
  },
  {
    id: "2",
    patient: "Michael Brown",
    doctor: "Dr. Wilson",
    date: "2024-10-25",
    time: "10:30 AM",
    type: "follow-up" as const,
    status: "in-progress" as const,
    price: 100,
    notes: "Follow-up for diabetes",
  },
  {
    id: "3",
    patient: "Emma Davis",
    doctor: "Dr. Johnson",
    date: "2024-10-25",
    time: "02:00 PM",
    type: "checkup" as const,
    status: "scheduled" as const,
    price: 120,
    notes: "Annual health checkup",
  },
  {
    id: "4",
    patient: "James Wilson",
    doctor: "Dr. Smith",
    date: "2024-10-26",
    time: "09:30 AM",
    type: "emergency" as const,
    status: "scheduled" as const,
    price: 200,
    notes: "Chest pain evaluation",
  },
  {
    id: "5",
    patient: "Lisa Anderson",
    doctor: "Dr. Martinez",
    date: "2024-10-26",
    time: "11:00 AM",
    type: "consultation" as const,
    status: "confirmed" as const,
    price: 150,
    notes: "Migraine consultation",
  },
  {
    id: "6",
    patient: "David Martinez",
    doctor: "Dr. Wilson",
    date: "2024-10-26",
    time: "01:30 PM",
    type: "follow-up" as const,
    status: "completed" as const,
    price: 100,
    notes: "Cholesterol follow-up",
  },
  {
    id: "7",
    patient: "Jennifer Taylor",
    doctor: "Dr. Rodriguez",
    date: "2024-10-27",
    time: "10:00 AM",
    type: "checkup" as const,
    status: "confirmed" as const,
    price: 180,
    notes: "Prenatal checkup",
  },
  {
    id: "8",
    patient: "Robert Garcia",
    doctor: "Dr. Smith",
    date: "2024-10-27",
    time: "02:00 PM",
    type: "consultation" as const,
    status: "scheduled" as const,
    price: 200,
    notes: "Cardiology consultation",
  },
  {
    id: "9",
    patient: "Amanda White",
    doctor: "Dr. Johnson",
    date: "2024-10-28",
    time: "09:00 AM",
    type: "emergency" as const,
    status: "completed" as const,
    price: 250,
    notes: "Allergic reaction treatment",
  },
  {
    id: "10",
    patient: "Christopher Lee",
    doctor: "Dr. Martinez",
    date: "2024-10-28",
    time: "11:30 AM",
    type: "follow-up" as const,
    status: "confirmed" as const,
    price: 120,
    notes: "Physical therapy progress",
  },
  {
    id: "11",
    patient: "Michelle Thompson",
    doctor: "Dr. Rodriguez",
    date: "2024-10-29",
    time: "10:30 AM",
    type: "consultation" as const,
    status: "scheduled" as const,
    price: 160,
    notes: "Mental health consultation",
  },
  {
    id: "12",
    patient: "William Harris",
    doctor: "Dr. Wilson",
    date: "2024-10-29",
    time: "03:00 PM",
    type: "checkup" as const,
    status: "confirmed" as const,
    price: 140,
    notes: "Kidney function check",
  },
  {
    id: "13",
    patient: "Jessica Clark",
    doctor: "Dr. Smith",
    date: "2024-10-30",
    time: "09:30 AM",
    type: "follow-up" as const,
    status: "scheduled" as const,
    price: 130,
    notes: "Autoimmune condition follow-up",
  },
  {
    id: "14",
    patient: "Matthew Rodriguez",
    doctor: "Dr. Johnson",
    date: "2024-10-30",
    time: "01:00 PM",
    type: "checkup" as const,
    status: "confirmed" as const,
    price: 120,
    notes: "Annual physical exam",
  },
  {
    id: "15",
    patient: "Ashley Lewis",
    doctor: "Dr. Martinez",
    date: "2024-10-31",
    time: "10:00 AM",
    type: "consultation" as const,
    status: "scheduled" as const,
    price: 170,
    notes: "Nutritional counseling",
  },
  {
    id: "16",
    patient: "Sarah Johnson",
    doctor: "Dr. Rodriguez",
    date: "2024-11-01",
    time: "11:00 AM",
    type: "follow-up" as const,
    status: "scheduled" as const,
    price: 110,
    notes: "Blood pressure follow-up",
  },
  {
    id: "17",
    patient: "Michael Brown",
    doctor: "Dr. Smith",
    date: "2024-11-01",
    time: "02:30 PM",
    type: "checkup" as const,
    status: "scheduled" as const,
    price: 125,
    notes: "Diabetes management review",
  },
  {
    id: "18",
    patient: "Emma Davis",
    doctor: "Dr. Wilson",
    date: "2024-11-02",
    time: "09:00 AM",
    type: "consultation" as const,
    status: "scheduled" as const,
    price: 155,
    notes: "Asthma management",
  },
  {
    id: "19",
    patient: "James Wilson",
    doctor: "Dr. Johnson",
    date: "2024-11-02",
    time: "03:30 PM",
    type: "follow-up" as const,
    status: "scheduled" as const,
    price: 115,
    notes: "Post-surgery follow-up",
  },
  {
    id: "20",
    patient: "Lisa Anderson",
    doctor: "Dr. Martinez",
    date: "2024-11-03",
    time: "10:30 AM",
    type: "emergency" as const,
    status: "scheduled" as const,
    price: 220,
    notes: "Severe headache evaluation",
  },
];
