export const mockBillingRecords = [
  {
    id: "bill1",
    patientId: "1",
    patientName: "Sarah Johnson",
    appointmentId: "1",
    invoiceNumber: "INV-2024-001",
    date: "2024-10-20",
    dueDate: "2024-11-19",
    services: [
      {
        code: "99213",
        description: "Office Visit - Established Patient",
        quantity: 1,
        unitPrice: 150.0,
        total: 150.0,
      },
      {
        code: "93000",
        description: "Electrocardiogram",
        quantity: 1,
        unitPrice: 75.0,
        total: 75.0,
      },
    ],
    subtotal: 225.0,
    tax: 0.0,
    discount: 0.0,
    totalAmount: 225.0,
    paidAmount: 225.0,
    balanceAmount: 0.0,
    paymentMethod: "insurance" as const,
    insuranceProvider: "Blue Cross Blue Shield",
    insuranceClaimId: "CLM-2024-001",
    status: "paid" as const,
    notes: "Covered by insurance - copay collected",
  },
  {
    id: "bill2",
    patientId: "2",
    patientName: "Michael Brown",
    appointmentId: "2",
    invoiceNumber: "INV-2024-002",
    date: "2024-10-18",
    dueDate: "2024-11-17",
    services: [
      {
        code: "99214",
        description: "Office Visit - Detailed",
        quantity: 1,
        unitPrice: 200.0,
        total: 200.0,
      },
      {
        code: "80053",
        description: "Comprehensive Metabolic Panel",
        quantity: 1,
        unitPrice: 85.0,
        total: 85.0,
      },
    ],
    subtotal: 285.0,
    tax: 0.0,
    discount: 15.0,
    totalAmount: 270.0,
    paidAmount: 50.0,
    balanceAmount: 220.0,
    paymentMethod: "partial" as const,
    insuranceProvider: "Aetna",
    insuranceClaimId: "CLM-2024-002",
    status: "partial" as const,
    notes: "Insurance pending - patient paid copay",
  },
  {
    id: "bill3",
    patientId: "3",
    patientName: "Emma Davis",
    appointmentId: "3",
    invoiceNumber: "INV-2024-003",
    date: "2024-10-15",
    dueDate: "2024-11-14",
    services: [
      {
        code: "99285",
        description: "Emergency Department Visit - High Complexity",
        quantity: 1,
        unitPrice: 450.0,
        total: 450.0,
      },
      {
        code: "94640",
        description: "Nebulizer Treatment",
        quantity: 2,
        unitPrice: 35.0,
        total: 70.0,
      },
      {
        code: "71020",
        description: "Chest X-Ray",
        quantity: 1,
        unitPrice: 120.0,
        total: 120.0,
      },
    ],
    subtotal: 640.0,
    tax: 0.0,
    discount: 0.0,
    totalAmount: 640.0,
    paidAmount: 0.0,
    balanceAmount: 640.0,
    paymentMethod: "pending" as const,
    insuranceProvider: "United Healthcare",
    insuranceClaimId: "CLM-2024-003",
    status: "pending" as const,
    notes: "Emergency visit - insurance authorization pending",
  },
  {
    id: "bill4",
    patientId: "4",
    patientName: "James Wilson",
    appointmentId: "4",
    invoiceNumber: "INV-2024-004",
    date: "2024-10-22",
    dueDate: "2024-11-21",
    services: [
      {
        code: "99213",
        description: "Office Visit - Established Patient",
        quantity: 1,
        unitPrice: 150.0,
        total: 150.0,
      },
    ],
    subtotal: 150.0,
    tax: 0.0,
    discount: 0.0,
    totalAmount: 150.0,
    paidAmount: 150.0,
    balanceAmount: 0.0,
    paymentMethod: "cash" as const,
    status: "paid" as const,
    notes: "Self-pay patient - cash payment received",
  },
  {
    id: "bill5",
    patientId: "5",
    patientName: "Lisa Anderson",
    appointmentId: "5",
    invoiceNumber: "INV-2024-005",
    date: "2024-10-19",
    dueDate: "2024-12-18",
    services: [
      {
        code: "99214",
        description: "Office Visit - Detailed",
        quantity: 1,
        unitPrice: 200.0,
        total: 200.0,
      },
      {
        code: "70450",
        description: "CT Head without Contrast",
        quantity: 1,
        unitPrice: 350.0,
        total: 350.0,
      },
    ],
    subtotal: 550.0,
    tax: 0.0,
    discount: 0.0,
    totalAmount: 550.0,
    paidAmount: 0.0,
    balanceAmount: 550.0,
    paymentMethod: "pending" as const,
    status: "overdue" as const,
    notes: "Payment overdue - follow up required",
  },
];

export const mockInsuranceProviders = [
  {
    id: "ins1",
    name: "Blue Cross Blue Shield",
    type: "PPO" as const,
    contactPhone: "+1 (800) 555-0001",
    contactEmail: "providers@bcbs.com",
    claimsAddress: "123 Insurance Plaza, Claims City, CC 12345",
    electronicSubmission: true,
    averagePaymentDays: 14,
    copayAmount: 25.0,
    deductible: 500.0,
    status: "active" as const,
  },
  {
    id: "ins2",
    name: "Aetna",
    type: "HMO" as const,
    contactPhone: "+1 (800) 555-0002",
    contactEmail: "providers@aetna.com",
    claimsAddress: "456 Health Ave, Benefits Town, BT 67890",
    electronicSubmission: true,
    averagePaymentDays: 21,
    copayAmount: 30.0,
    deductible: 750.0,
    status: "active" as const,
  },
  {
    id: "ins3",
    name: "United Healthcare",
    type: "PPO" as const,
    contactPhone: "+1 (800) 555-0003",
    contactEmail: "providers@uhc.com",
    claimsAddress: "789 Coverage Blvd, Insurance Valley, IV 11111",
    electronicSubmission: true,
    averagePaymentDays: 18,
    copayAmount: 20.0,
    deductible: 1000.0,
    status: "active" as const,
  },
  {
    id: "ins4",
    name: "Cigna",
    type: "HMO" as const,
    contactPhone: "+1 (800) 555-0004",
    contactEmail: "providers@cigna.com",
    claimsAddress: "321 Wellness Way, Health City, HC 22222",
    electronicSubmission: false,
    averagePaymentDays: 28,
    copayAmount: 35.0,
    deductible: 500.0,
    status: "active" as const,
  },
];

export const mockPayments = [
  {
    id: "pay1",
    billingId: "bill1",
    patientName: "Sarah Johnson",
    amount: 225.0,
    paymentDate: "2024-10-20",
    paymentMethod: "insurance" as const,
    referenceNumber: "INS-2024-001",
    status: "completed" as const,
    processedBy: "Jennifer Thompson",
  },
  {
    id: "pay2",
    billingId: "bill2",
    patientName: "Michael Brown",
    amount: 50.0,
    paymentDate: "2024-10-18",
    paymentMethod: "credit-card" as const,
    referenceNumber: "CC-2024-002",
    status: "completed" as const,
    processedBy: "Jennifer Thompson",
  },
  {
    id: "pay3",
    billingId: "bill4",
    patientName: "James Wilson",
    amount: 150.0,
    paymentDate: "2024-10-22",
    paymentMethod: "cash" as const,
    referenceNumber: "CASH-2024-001",
    status: "completed" as const,
    processedBy: "Maria Rodriguez",
  },
];
