export const mockClinics = [
  {
    id: "1",
    name: "City Medical Center",
    address: "123 Main St, Downtown",
    phone: "+1 (555) 123-4567",
    email: "info@citymedical.com",
    status: "active" as const,
    subscription: "premium" as const,
    patientCount: 450,
    dailyAppointments: 25,
  },
  {
    id: "2",
    name: "Downtown Health Clinic",
    address: "456 Oak Ave, Central District",
    phone: "+1 (555) 987-6543",
    email: "contact@downtownhealth.com",
    status: "active" as const,
    subscription: "basic" as const,
    patientCount: 280,
    dailyAppointments: 15,
  },
  {
    id: "3",
    name: "Westside Family Practice",
    address: "789 Pine Rd, Westside",
    phone: "+1 (555) 456-7890",
    email: "hello@westsidehealth.com",
    status: "inactive" as const,
    subscription: "enterprise" as const,
    patientCount: 650,
    dailyAppointments: 35,
  },
  {
    id: "4",
    name: "Northside Medical Group",
    address: "321 Elm St, Northside",
    phone: "+1 (555) 234-5678",
    email: "contact@northsidemedical.com",
    status: "active" as const,
    subscription: "premium" as const,
    patientCount: 380,
    dailyAppointments: 22,
  },
  {
    id: "5",
    name: "Southpark Health Center",
    address: "654 Maple Ave, Southpark",
    phone: "+1 (555) 345-6789",
    email: "info@southparkhealth.com",
    status: "active" as const,
    subscription: "basic" as const,
    patientCount: 195,
    dailyAppointments: 12,
  },
  {
    id: "6",
    name: "East Valley Clinic",
    address: "987 Cedar Blvd, East Valley",
    phone: "+1 (555) 456-7890",
    email: "hello@eastvalley.com",
    status: "active" as const,
    subscription: "enterprise" as const,
    patientCount: 520,
    dailyAppointments: 28,
  },
  {
    id: "7",
    name: "West Hills Medical",
    address: "147 Birch Lane, West Hills",
    phone: "+1 (555) 567-8901",
    email: "contact@westhillsmed.com",
    status: "inactive" as const,
    subscription: "basic" as const,
    patientCount: 150,
    dailyAppointments: 8,
  },
  {
    id: "8",
    name: "Central Park Clinic",
    address: "258 Park Ave, Central",
    phone: "+1 (555) 678-9012",
    email: "info@centralparkmed.com",
    status: "active" as const,
    subscription: "premium" as const,
    patientCount: 420,
    dailyAppointments: 24,
  },
  {
    id: "9",
    name: "Riverside Health Services",
    address: "369 River Rd, Riverside",
    phone: "+1 (555) 789-0123",
    email: "contact@riversidehealth.com",
    status: "active" as const,
    subscription: "enterprise" as const,
    patientCount: 680,
    dailyAppointments: 32,
  },
  {
    id: "10",
    name: "Mountain View Medical",
    address: "741 Summit Dr, Mountain View",
    phone: "+1 (555) 890-1234",
    email: "hello@mountainviewmed.com",
    status: "active" as const,
    subscription: "basic" as const,
    patientCount: 220,
    dailyAppointments: 14,
  },
  {
    id: "11",
    name: "Lakeside Family Practice",
    address: "852 Lake Shore Dr, Lakeside",
    phone: "+1 (555) 901-2345",
    email: "info@lakesidehealth.com",
    status: "active" as const,
    subscription: "premium" as const,
    patientCount: 340,
    dailyAppointments: 19,
  },
  {
    id: "12",
    name: "Sunset Medical Center",
    address: "963 Sunset Blvd, Sunset",
    phone: "+1 (555) 012-3456",
    email: "contact@sunsetmedical.com",
    status: "inactive" as const,
    subscription: "basic" as const,
    patientCount: 180,
    dailyAppointments: 10,
  },
];
