export const mockPatients = [
  {
    id: "1",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@email.com",
    phone: "+1 (555) 123-4567",
    dateOfBirth: "1985-03-15",
    gender: "female" as const,
    bloodType: "A+",
    allergies: ["Penicillin", "Peanuts"],
    emergencyContact: "John Johnson",
    emergencyPhone: "+1 (555) 123-4568",
    medicalNotes: "Hypertension, regular checkups needed",
    lastVisit: "2024-10-20",
  },
  {
    id: "2",
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@email.com",
    phone: "+1 (555) 987-6543",
    dateOfBirth: "1978-07-22",
    gender: "male" as const,
    bloodType: "O-",
    allergies: [],
    emergencyContact: "Lisa Brown",
    emergencyPhone: "+1 (555) 987-6544",
    medicalNotes: "Diabetes type 2, insulin dependent",
    lastVisit: "2024-10-18",
  },
  {
    id: "3",
    firstName: "Emma",
    lastName: "Davis",
    email: "emma.davis@email.com",
    phone: "+1 (555) 456-7890",
    dateOfBirth: "1992-11-08",
    gender: "female" as const,
    bloodType: "B+",
    allergies: ["Shellfish"],
    emergencyContact: "David Davis",
    emergencyPhone: "+1 (555) 456-7891",
    medicalNotes: "Asthma, carries inhaler",
    lastVisit: "2024-10-15",
  },
  {
    id: "4",
    firstName: "James",
    lastName: "Wilson",
    email: "james.wilson@email.com",
    phone: "+1 (555) 234-5678",
    dateOfBirth: "1990-12-03",
    gender: "male" as const,
    bloodType: "AB+",
    allergies: ["Latex"],
    emergencyContact: "Mary Wilson",
    emergencyPhone: "+1 (555) 234-5679",
    medicalNotes: "Recent surgery, follow-up required",
    lastVisit: "2024-10-22",
  },
  {
    id: "5",
    firstName: "Lisa",
    lastName: "Anderson",
    email: "lisa.anderson@email.com",
    phone: "+1 (555) 345-6789",
    dateOfBirth: "1982-06-18",
    gender: "female" as const,
    bloodType: "O+",
    allergies: ["Aspirin", "Codeine"],
    emergencyContact: "Robert Anderson",
    emergencyPhone: "+1 (555) 345-6790",
    medicalNotes: "Chronic migraines, medication management",
    lastVisit: "2024-10-19",
  },
  {
    id: "6",
    firstName: "David",
    lastName: "Martinez",
    email: "david.martinez@email.com",
    phone: "+1 (555) 456-7890",
    dateOfBirth: "1975-09-25",
    gender: "male" as const,
    bloodType: "A-",
    allergies: [],
    emergencyContact: "Sofia Martinez",
    emergencyPhone: "+1 (555) 456-7891",
    medicalNotes: "High cholesterol, diet monitoring",
    lastVisit: "2024-10-17",
  },
  {
    id: "7",
    firstName: "Jennifer",
    lastName: "Taylor",
    email: "jennifer.taylor@email.com",
    phone: "+1 (555) 567-8901",
    dateOfBirth: "1988-04-12",
    gender: "female" as const,
    bloodType: "B-",
    allergies: ["Sulfa drugs"],
    emergencyContact: "Mark Taylor",
    emergencyPhone: "+1 (555) 567-8902",
    medicalNotes: "Pregnancy monitoring, second trimester",
    lastVisit: "2024-10-21",
  },
  {
    id: "8",
    firstName: "Robert",
    lastName: "Garcia",
    email: "robert.garcia@email.com",
    phone: "+1 (555) 678-9012",
    dateOfBirth: "1965-11-30",
    gender: "male" as const,
    bloodType: "O-",
    allergies: ["Iodine"],
    emergencyContact: "Carmen Garcia",
    emergencyPhone: "+1 (555) 678-9013",
    medicalNotes: "Heart condition, regular monitoring",
    lastVisit: "2024-10-16",
  },
  {
    id: "9",
    firstName: "Amanda",
    lastName: "White",
    email: "amanda.white@email.com",
    phone: "+1 (555) 789-0123",
    dateOfBirth: "1993-02-14",
    gender: "female" as const,
    bloodType: "AB-",
    allergies: ["Nuts", "Eggs"],
    emergencyContact: "Kevin White",
    emergencyPhone: "+1 (555) 789-0124",
    medicalNotes: "Severe allergies, carries EpiPen",
    lastVisit: "2024-10-23",
  },
  {
    id: "10",
    firstName: "Christopher",
    lastName: "Lee",
    email: "christopher.lee@email.com",
    phone: "+1 (555) 890-1234",
    dateOfBirth: "1980-08-07",
    gender: "male" as const,
    bloodType: "A+",
    allergies: [],
    emergencyContact: "Susan Lee",
    emergencyPhone: "+1 (555) 890-1235",
    medicalNotes: "Sports injury recovery, physical therapy",
    lastVisit: "2024-10-18",
  },
  {
    id: "11",
    firstName: "Michelle",
    lastName: "Thompson",
    email: "michelle.thompson@email.com",
    phone: "+1 (555) 901-2345",
    dateOfBirth: "1987-01-22",
    gender: "female" as const,
    bloodType: "B+",
    allergies: ["Morphine"],
    emergencyContact: "Daniel Thompson",
    emergencyPhone: "+1 (555) 901-2346",
    medicalNotes: "Anxiety disorder, therapy sessions",
    lastVisit: "2024-10-20",
  },
  {
    id: "12",
    firstName: "William",
    lastName: "Harris",
    email: "william.harris@email.com",
    phone: "+1 (555) 012-3456",
    dateOfBirth: "1972-05-16",
    gender: "male" as const,
    bloodType: "O+",
    allergies: ["Contrast dye"],
    emergencyContact: "Patricia Harris",
    emergencyPhone: "+1 (555) 012-3457",
    medicalNotes: "Kidney stones, dietary restrictions",
    lastVisit: "2024-10-14",
  },
  {
    id: "13",
    firstName: "Jessica",
    lastName: "Clark",
    email: "jessica.clark@email.com",
    phone: "+1 (555) 123-4567",
    dateOfBirth: "1991-10-09",
    gender: "female" as const,
    bloodType: "A-",
    allergies: ["Antibiotics"],
    emergencyContact: "Ryan Clark",
    emergencyPhone: "+1 (555) 123-4568",
    medicalNotes: "Autoimmune condition, immunosuppressants",
    lastVisit: "2024-10-22",
  },
  {
    id: "14",
    firstName: "Matthew",
    lastName: "Rodriguez",
    email: "matthew.rodriguez@email.com",
    phone: "+1 (555) 234-5678",
    dateOfBirth: "1983-07-28",
    gender: "male" as const,
    bloodType: "B-",
    allergies: [],
    emergencyContact: "Elena Rodriguez",
    emergencyPhone: "+1 (555) 234-5679",
    medicalNotes: "Routine checkup, all normal",
    lastVisit: "2024-10-19",
  },
  {
    id: "15",
    firstName: "Ashley",
    lastName: "Lewis",
    email: "ashley.lewis@email.com",
    phone: "+1 (555) 345-6789",
    dateOfBirth: "1989-03-11",
    gender: "female" as const,
    bloodType: "AB+",
    allergies: ["Shellfish", "Dairy"],
    emergencyContact: "Brandon Lewis",
    emergencyPhone: "+1 (555) 345-6790",
    medicalNotes: "Food allergies, nutritional counseling",
    lastVisit: "2024-10-21",
  },
];
