export const mockStaff = [
  {
    id: "staff1",
    firstName: "Maria",
    lastName: "Rodriguez",
    email: "maria.rodriguez@clinic.com",
    phone: "+1 (555) 300-1001",
    role: "nurse" as const,
    department: "General Medicine",
    employeeId: "EMP001",
    hireDate: "2020-03-15",
    shift: "day" as const,
    status: "active" as const,
    certifications: ["RN", "BLS", "ACLS"],
    specializations: ["Pediatric Care", "Wound Care"],
    supervisor: "Dr. John Smith",
    salary: 65000,
    schedule: "Mon-Fri 7AM-3PM",
  },
  {
    id: "staff2",
    firstName: "Jennifer",
    lastName: "Thompson",
    email: "jennifer.thompson@clinic.com",
    phone: "+1 (555) 300-1002",
    role: "receptionist" as const,
    department: "Administration",
    employeeId: "EMP002",
    hireDate: "2021-07-20",
    shift: "day" as const,
    status: "active" as const,
    certifications: ["Medical Office Administration"],
    specializations: ["Patient Scheduling", "Insurance Verification"],
    supervisor: "Office Manager",
    salary: 38000,
    schedule: "Mon-Fri 8AM-5PM",
  },
  {
    id: "staff3",
    firstName: "Robert",
    lastName: "Chen",
    email: "robert.chen@clinic.com",
    phone: "+1 (555) 300-1003",
    role: "lab-technician" as const,
    department: "Laboratory",
    employeeId: "EMP003",
    hireDate: "2019-11-10",
    shift: "day" as const,
    status: "active" as const,
    certifications: ["MLT", "Phlebotomy", "Clinical Chemistry"],
    specializations: ["Blood Analysis", "Microbiology"],
    supervisor: "Lab Director",
    salary: 52000,
    schedule: "Mon-Fri 6AM-2PM",
  },
  {
    id: "staff4",
    firstName: "Lisa",
    lastName: "Parker",
    email: "lisa.parker@clinic.com",
    phone: "+1 (555) 300-1004",
    role: "nurse" as const,
    department: "Emergency",
    employeeId: "EMP004",
    hireDate: "2018-05-22",
    shift: "night" as const,
    status: "active" as const,
    certifications: ["RN", "CEN", "TNCC", "BLS"],
    specializations: ["Emergency Care", "Trauma", "Critical Care"],
    supervisor: "Charge Nurse",
    salary: 72000,
    schedule: "Mon-Wed-Fri 7PM-7AM",
  },
  {
    id: "staff5",
    firstName: "David",
    lastName: "Williams",
    email: "david.williams@clinic.com",
    phone: "+1 (555) 300-1005",
    role: "pharmacist" as const,
    department: "Pharmacy",
    employeeId: "EMP005",
    hireDate: "2017-09-08",
    shift: "day" as const,
    status: "active" as const,
    certifications: ["PharmD", "Board Certified Pharmacist"],
    specializations: ["Clinical Pharmacy", "Medication Therapy Management"],
    supervisor: "Pharmacy Director",
    salary: 125000,
    schedule: "Mon-Fri 9AM-6PM",
  },
  {
    id: "staff6",
    firstName: "Amanda",
    lastName: "Davis",
    email: "amanda.davis@clinic.com",
    phone: "+1 (555) 300-1006",
    role: "medical-assistant" as const,
    department: "Cardiology",
    employeeId: "EMP006",
    hireDate: "2022-01-15",
    shift: "day" as const,
    status: "active" as const,
    certifications: ["CMA", "EKG Technician", "BLS"],
    specializations: ["Vital Signs", "EKG", "Patient Prep"],
    supervisor: "Dr. Michael Johnson",
    salary: 42000,
    schedule: "Tue-Sat 8AM-4PM",
  },
  {
    id: "staff7",
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@clinic.com",
    phone: "+1 (555) 300-1007",
    role: "it-support" as const,
    department: "Information Technology",
    employeeId: "EMP007",
    hireDate: "2020-12-01",
    shift: "day" as const,
    status: "active" as const,
    certifications: ["CompTIA A+", "Network+", "HIPAA Compliance"],
    specializations: ["EMR Systems", "Network Security", "Hardware Support"],
    supervisor: "IT Director",
    salary: 58000,
    schedule: "Mon-Fri 8AM-5PM",
  },
  {
    id: "staff8",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@clinic.com",
    phone: "+1 (555) 300-1008",
    role: "billing-specialist" as const,
    department: "Billing",
    employeeId: "EMP008",
    hireDate: "2019-04-18",
    shift: "day" as const,
    status: "active" as const,
    certifications: ["CPC", "Medical Billing & Coding"],
    specializations: ["Insurance Claims", "Payment Processing", "Coding"],
    supervisor: "Billing Manager",
    salary: 45000,
    schedule: "Mon-Fri 9AM-5PM",
  },
  {
    id: "staff9",
    firstName: "Kevin",
    lastName: "Martinez",
    email: "kevin.martinez@clinic.com",
    phone: "+1 (555) 300-1009",
    role: "security" as const,
    department: "Security",
    employeeId: "EMP009",
    hireDate: "2021-08-30",
    shift: "night" as const,
    status: "active" as const,
    certifications: ["Security Guard License", "CPR", "First Aid"],
    specializations: ["Facility Security", "Emergency Response"],
    supervisor: "Security Supervisor",
    salary: 35000,
    schedule: "Sun-Thu 11PM-7AM",
  },
  {
    id: "staff10",
    firstName: "Rachel",
    lastName: "White",
    email: "rachel.white@clinic.com",
    phone: "+1 (555) 300-1010",
    role: "social-worker" as const,
    department: "Patient Services",
    employeeId: "EMP010",
    hireDate: "2020-06-12",
    shift: "day" as const,
    status: "active" as const,
    certifications: ["MSW", "LCSW", "Case Management"],
    specializations: [
      "Patient Advocacy",
      "Discharge Planning",
      "Crisis Intervention",
    ],
    supervisor: "Patient Services Director",
    salary: 62000,
    schedule: "Mon-Fri 8AM-4PM",
  },
];

export const mockSchedules = [
  {
    id: "sch1",
    staffId: "staff1",
    staffName: "Maria Rodriguez",
    role: "nurse",
    date: "2024-10-25",
    shift: "day" as const,
    startTime: "07:00",
    endTime: "15:00",
    department: "General Medicine",
    status: "scheduled" as const,
  },
  {
    id: "sch2",
    staffId: "staff4",
    staffName: "Lisa Parker",
    role: "nurse",
    date: "2024-10-25",
    shift: "night" as const,
    startTime: "19:00",
    endTime: "07:00",
    department: "Emergency",
    status: "scheduled" as const,
  },
  {
    id: "sch3",
    staffId: "staff2",
    staffName: "Jennifer Thompson",
    role: "receptionist",
    date: "2024-10-25",
    shift: "day" as const,
    startTime: "08:00",
    endTime: "17:00",
    department: "Administration",
    status: "scheduled" as const,
  },
  {
    id: "sch4",
    staffId: "staff3",
    staffName: "Robert Chen",
    role: "lab-technician",
    date: "2024-10-25",
    shift: "day" as const,
    startTime: "06:00",
    endTime: "14:00",
    department: "Laboratory",
    status: "scheduled" as const,
  },
];
