export const mockDoctors = [
  {
    id: "doc1",
    firstName: "John",
    lastName: "Smith",
    email: "dr.smith@clinic.com",
    phone: "+1 (555) 101-2001",
    specialization: "Cardiology",
    licenseNumber: "MD-12345",
    experience: 15,
    education: "Harvard Medical School",
    status: "active" as const,
    schedule: "Mon-Fri 9AM-5PM",
    patientsCount: 245,
    appointmentsToday: 8,
    rating: 4.9,
    joinedDate: "2018-03-15",
    clinicId: "1",
    clinicName: "City Medical Center",
  },
  {
    id: "doc2",
    firstName: "Emily",
    lastName: "Wilson",
    email: "dr.wilson@clinic.com",
    phone: "+1 (555) 102-2002",
    specialization: "Pediatrics",
    licenseNumber: "MD-23456",
    experience: 12,
    education: "Johns Hopkins University",
    status: "active" as const,
    schedule: "Mon-Wed-Fri 8AM-4PM",
    patientsCount: 189,
    appointmentsToday: 6,
    rating: 4.8,
    joinedDate: "2019-07-22",
    clinicId: "1",
    clinicName: "City Medical Center",
  },
  {
    id: "doc3",
    firstName: "Michael",
    lastName: "Johnson",
    email: "dr.johnson@clinic.com",
    phone: "+1 (555) 103-2003",
    specialization: "Orthopedics",
    licenseNumber: "MD-34567",
    experience: 20,
    education: "Stanford Medical School",
    status: "active" as const,
    schedule: "Tue-Thu-Sat 10AM-6PM",
    patientsCount: 312,
    appointmentsToday: 5,
    rating: 4.7,
    joinedDate: "2015-11-08",
    clinicId: "2",
    clinicName: "Downtown Health Clinic",
  },
  {
    id: "doc4",
    firstName: "Sarah",
    lastName: "Martinez",
    email: "dr.martinez@clinic.com",
    phone: "+1 (555) 104-2004",
    specialization: "Dermatology",
    licenseNumber: "MD-45678",
    experience: 8,
    education: "UCLA Medical School",
    status: "active" as const,
    schedule: "Mon-Thu 9AM-3PM",
    patientsCount: 156,
    appointmentsToday: 4,
    rating: 4.9,
    joinedDate: "2021-02-14",
    clinicId: "1",
    clinicName: "City Medical Center",
  },
  {
    id: "doc5",
    firstName: "David",
    lastName: "Rodriguez",
    email: "dr.rodriguez@clinic.com",
    phone: "+1 (555) 105-2005",
    specialization: "Neurology",
    licenseNumber: "MD-56789",
    experience: 18,
    education: "Mayo Clinic College of Medicine",
    status: "active" as const,
    schedule: "Mon-Fri 8AM-4PM",
    patientsCount: 278,
    appointmentsToday: 7,
    rating: 4.8,
    joinedDate: "2017-09-30",
    clinicId: "3",
    clinicName: "Westside Family Practice",
  },
  {
    id: "doc6",
    firstName: "Lisa",
    lastName: "Thompson",
    email: "dr.thompson@clinic.com",
    phone: "+1 (555) 106-2006",
    specialization: "Psychiatry",
    licenseNumber: "MD-67890",
    experience: 14,
    education: "Columbia University",
    status: "on-leave" as const,
    schedule: "Currently on leave",
    patientsCount: 198,
    appointmentsToday: 0,
    rating: 4.6,
    joinedDate: "2019-01-12",
    clinicId: "2",
    clinicName: "Downtown Health Clinic",
  },
  {
    id: "doc7",
    firstName: "Robert",
    lastName: "Anderson",
    email: "dr.anderson@clinic.com",
    phone: "+1 (555) 107-2007",
    specialization: "General Medicine",
    licenseNumber: "MD-78901",
    experience: 25,
    education: "University of Pennsylvania",
    status: "active" as const,
    schedule: "Mon-Fri 7AM-3PM",
    patientsCount: 445,
    appointmentsToday: 9,
    rating: 4.9,
    joinedDate: "2012-05-18",
    clinicId: "1",
    clinicName: "City Medical Center",
  },
  {
    id: "doc8",
    firstName: "Jennifer",
    lastName: "Lee",
    email: "dr.lee@clinic.com",
    phone: "+1 (555) 108-2008",
    specialization: "Gynecology",
    licenseNumber: "MD-89012",
    experience: 11,
    education: "University of Chicago",
    status: "active" as const,
    schedule: "Tue-Fri 9AM-5PM",
    patientsCount: 223,
    appointmentsToday: 6,
    rating: 4.8,
    joinedDate: "2020-08-03",
    clinicId: "4",
    clinicName: "Northside Medical Group",
  },
  {
    id: "doc9",
    firstName: "Christopher",
    lastName: "Garcia",
    email: "dr.garcia@clinic.com",
    phone: "+1 (555) 109-2009",
    specialization: "Radiology",
    licenseNumber: "MD-90123",
    experience: 16,
    education: "Duke University",
    status: "active" as const,
    schedule: "Mon-Wed-Fri 8AM-6PM",
    patientsCount: 167,
    appointmentsToday: 3,
    rating: 4.7,
    joinedDate: "2016-12-01",
    clinicId: "2",
    clinicName: "Downtown Health Clinic",
  },
  {
    id: "doc10",
    firstName: "Amanda",
    lastName: "White",
    email: "dr.white@clinic.com",
    phone: "+1 (555) 110-2010",
    specialization: "Endocrinology",
    licenseNumber: "MD-01234",
    experience: 9,
    education: "Vanderbilt University",
    status: "active" as const,
    schedule: "Mon-Thu 10AM-4PM",
    patientsCount: 134,
    appointmentsToday: 5,
    rating: 4.8,
    joinedDate: "2022-04-25",
    clinicId: "5",
    clinicName: "Southpark Health Center",
  },
  {
    id: "doc11",
    firstName: "Kevin",
    lastName: "Brown",
    email: "dr.brown@clinic.com",
    phone: "+1 (555) 111-2011",
    specialization: "Ophthalmology",
    licenseNumber: "MD-11223",
    experience: 13,
    education: "University of Michigan",
    status: "inactive" as const,
    schedule: "Currently inactive",
    patientsCount: 89,
    appointmentsToday: 0,
    rating: 4.5,
    joinedDate: "2018-10-14",
    clinicId: "3",
    clinicName: "Westside Family Practice",
  },
  {
    id: "doc12",
    firstName: "Michelle",
    lastName: "Davis",
    email: "dr.davis@clinic.com",
    phone: "+1 (555) 112-2012",
    specialization: "Anesthesiology",
    licenseNumber: "MD-22334",
    experience: 17,
    education: "Washington University",
    status: "active" as const,
    schedule: "Mon-Fri 6AM-2PM",
    patientsCount: 201,
    appointmentsToday: 4,
    rating: 4.9,
    joinedDate: "2016-06-07",
    clinicId: "6",
    clinicName: "East Valley Clinic",
  },
];
