export const mockInventoryItems = [
  {
    id: "inv1",
    name: "Disposable Syringes (10ml)",
    category: "Medical Supplies" as const,
    currentStock: 250,
    minStock: 100,
    maxStock: 500,
    unit: "pieces",
    costPerUnit: 0.85,
    supplier: "MedSupply Co.",
    lastRestocked: "2024-10-15",
    expiryDate: "2025-10-15",
    location: "Storage Room A - Shelf 3",
    status: "in-stock" as const,
  },
  {
    id: "inv2",
    name: "Blood Pressure Cuffs",
    category: "Equipment" as const,
    currentStock: 8,
    minStock: 5,
    maxStock: 15,
    unit: "pieces",
    costPerUnit: 45.0,
    supplier: "Healthcare Equipment Ltd.",
    lastRestocked: "2024-09-20",
    location: "Equipment Room - Cabinet B",
    status: "in-stock" as const,
  },
  {
    id: "inv3",
    name: "Surgical Gloves (Size M)",
    category: "Medical Supplies" as const,
    currentStock: 45,
    minStock: 50,
    maxStock: 200,
    unit: "boxes",
    costPerUnit: 12.5,
    supplier: "SafeHands Medical",
    lastRestocked: "2024-10-10",
    expiryDate: "2026-10-10",
    location: "Storage Room A - Shelf 1",
    status: "low-stock" as const,
  },
  {
    id: "inv4",
    name: "Digital Thermometers",
    category: "Equipment" as const,
    currentStock: 12,
    minStock: 8,
    maxStock: 20,
    unit: "pieces",
    costPerUnit: 25.0,
    supplier: "TechMed Solutions",
    lastRestocked: "2024-10-05",
    location: "Equipment Room - Drawer 2",
    status: "in-stock" as const,
  },
  {
    id: "inv5",
    name: "Bandages (Assorted)",
    category: "Medical Supplies" as const,
    currentStock: 15,
    minStock: 25,
    maxStock: 100,
    unit: "boxes",
    costPerUnit: 8.75,
    supplier: "WoundCare Plus",
    lastRestocked: "2024-09-28",
    expiryDate: "2027-09-28",
    location: "Storage Room B - Shelf 2",
    status: "low-stock" as const,
  },
  {
    id: "inv6",
    name: "Stethoscopes",
    category: "Equipment" as const,
    currentStock: 6,
    minStock: 4,
    maxStock: 10,
    unit: "pieces",
    costPerUnit: 120.0,
    supplier: "Professional Medical Tools",
    lastRestocked: "2024-08-15",
    location: "Equipment Room - Cabinet A",
    status: "in-stock" as const,
  },
  {
    id: "inv7",
    name: "Alcohol Swabs",
    category: "Medical Supplies" as const,
    currentStock: 2,
    minStock: 10,
    maxStock: 50,
    unit: "boxes",
    costPerUnit: 3.25,
    supplier: "CleanCare Medical",
    lastRestocked: "2024-09-15",
    expiryDate: "2025-09-15",
    location: "Storage Room A - Shelf 2",
    status: "critical" as const,
  },
  {
    id: "inv8",
    name: "Examination Tables",
    category: "Furniture" as const,
    currentStock: 4,
    minStock: 3,
    maxStock: 6,
    unit: "pieces",
    costPerUnit: 850.0,
    supplier: "MedFurniture Pro",
    lastRestocked: "2024-06-01",
    location: "Examination Rooms",
    status: "in-stock" as const,
  },
  {
    id: "inv9",
    name: "Prescription Pads",
    category: "Office Supplies" as const,
    currentStock: 25,
    minStock: 15,
    maxStock: 50,
    unit: "pads",
    costPerUnit: 2.5,
    supplier: "Office Medical Supply",
    lastRestocked: "2024-10-12",
    location: "Office Supply Cabinet",
    status: "in-stock" as const,
  },
  {
    id: "inv10",
    name: "Pulse Oximeters",
    category: "Equipment" as const,
    currentStock: 3,
    minStock: 2,
    maxStock: 8,
    unit: "pieces",
    costPerUnit: 75.0,
    supplier: "VitalSigns Tech",
    lastRestocked: "2024-09-30",
    location: "Equipment Room - Cabinet C",
    status: "in-stock" as const,
  },
];

export const mockSuppliers = [
  {
    id: "sup1",
    name: "MedSupply Co.",
    contactPerson: "John Anderson",
    email: "orders@medsupply.com",
    phone: "+1 (555) 200-1001",
    address: "123 Medical District, Supply City, SC 12345",
    categories: ["Medical Supplies", "Pharmaceuticals"],
    rating: 4.8,
    paymentTerms: "Net 30",
    status: "active" as const,
  },
  {
    id: "sup2",
    name: "Healthcare Equipment Ltd.",
    contactPerson: "Sarah Mitchell",
    email: "sales@healthequip.com",
    phone: "+1 (555) 200-1002",
    address: "456 Equipment Ave, Tech Valley, TV 67890",
    categories: ["Equipment", "Technology"],
    rating: 4.6,
    paymentTerms: "Net 45",
    status: "active" as const,
  },
  {
    id: "sup3",
    name: "SafeHands Medical",
    contactPerson: "Mike Rodriguez",
    email: "info@safehands.com",
    phone: "+1 (555) 200-1003",
    address: "789 Safety Blvd, Protection City, PC 11111",
    categories: ["Medical Supplies", "Safety Equipment"],
    rating: 4.9,
    paymentTerms: "Net 30",
    status: "active" as const,
  },
];
